#!/bin/bash
#BSUB -J "BAM2mpileup[1-66]%33"
#BSUB -R "rusage[mem=2000]"
#BSUB -n 1
#BSUB -W 12:00
#BSUB -o ./logs/log.%J.%I
#BSUB -e ./errs/err.%J.%I

module load gdc gcc/4.9.2 samtools/1.8

output_dir="/cluster/project/gdc/people/lhirzi/GenomeScan/Dsyl/Chr_16"

IDX=$LSB_JOBINDEX
bamfile=`sed -n ${IDX}p <${output_dir}/extracted.bam.filelist.Chr16`
STEM=$(basename "${bamfile}" .sorted.bam)
samtools mpileup ${output_dir}/${bamfile} > ${output_dir}/${STEM}.mpileup
