#!/bin/bash
#BSUB -J "EnvAss[8,23]%2" 
#BSUB -W 24:00 
#BSUB -n 1
#BSUB -R "rusage[mem=5000]"
#BSUB -o ./logs/log.%J.%I
#BSUB -e ./errs/err.%J.%I

mkdir ./logs
mkdir ./errs

module load r
IDX=$LSB_JOBINDEX


SCAFF='scaffold4_size532381'

n=${IDX}

echo ${n}
Rscript Mantel_test_alleles_variables_v3.R \
'AF_Q20_'${SCAFF}'.txt' \
${SCAFF} \
Dsylvestris_all.txt \
6,4,2,5,1,3 \
chr,pos,Tsanfleuron_POP1.txt,Challer_POP2.txt,Saviese_POP3.txt,Saxon_POP4.txt,LacdeMauv_POP5.txt,Varen_POP6.txt \
no 1 1000000 \
${n} 999 \
global.fst.matrix.txt

