#!/bin/bash
#BSUB -J "angsdAsso[1]%1" 
#BSUB -W 24:00 
#BSUB -n 1
#BSUB -R "rusage[mem=20000]"
#BSUB -o ./logs/log.%J.%I
#BSUB -e ./errs/err.%J.%I

mkdir ./logs
mkdir ./errs

module load gcc/4.8.2 gdc angsd/0.917
module load r


# Remember that Ind   will be shifted of 1 after number 56 because this sample was removed (had no reads) !! 


IDX=$LSB_JOBINDEX

mHigh='5'
maf='0.1'


angsd -P 1 -bam bamfiles.txt -doAsso 2 -GL 1 -doPost 1  -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 1  -yQuant FloweringTime.txt  \
-out out.gwas  -minHigh ${m} -minMaf ${f} \
-cov cov.mat.pca.eVect1.2.txt 
