#!/bin/bash

#BSUB -J "thetastats[1-6]%6"
#BSUB -R "rusage[mem=10000]"
#BSUB -n 1
#BSUB -W 24:00
#BSUB -o ./thetastatslogs/log.%J.%I
#BSUB -e ./thetastatserrs/err.%J.%I

mkdir ./thetastatslogs/
mkdir ./thetastatserrs/

sw='500'
mkdir 'ite_'$sw


## set variables
thetasext='.thetas.idx'

module load gcc/4.8.2 gdc angsd/0.917


IDX=$LSB_JOBINDEX
BARCODES=`sed -n ${IDX}p < Dsyl_barcodes.txt`

saf1=$(echo $BARCODES | cut -f2 -d' ')


thetaStat do_stat \
${saf1}${thetasext} -win ${sw} -step ${sw} -outnames './ite_'${sw}'/'${saf1}'_w'${sw}'_s'${sw}'.thetasWindow'


